# Background and foreground colors
background = #f1f3ea
foreground = #1a1d05

# Standard colors
palette = 0=#f1f3ea
palette = 1=#585000
palette = 2=#50419a
palette = 3=#687013
palette = 4=#68559b
palette = 5=#527100
palette = 6=#8252ba
palette = 7=#1a1d05

# Bright colors
palette = 8=#83847d
palette = 9=#7a7300
palette = 10=#735ed0
palette = 11=#8a9605
palette = 12=#8d74ce
palette = 13=#719800
palette = 14=#aa6ef2
palette = 15=#373c1a
