$color = rgba(241, 243, 234, 1)
$inner_color = rgba(241, 243, 234, 0.66)
$outer_color = rgba(82, 113, 0, 1)
$font_color = rgba(26, 29, 5, 1)
$placeholder_color = rgba(26, 29, 5, 0.7)
$check_color = rgba(130, 82, 186, 1)
